import { describe, expect, it } from "vitest";
import {
  detectReportKind,
  reportContentType,
  safeReportFilename,
  validateReport,
} from "./report-upload";

const pdf = (extra = "") => Buffer.from(`%PDF-1.4\n${extra}`);
const html = (body: string) => Buffer.from(body);

const MAX = 20 * 1024 * 1024;

describe("detectReportKind", () => {
  it("recognises a PDF by its magic bytes", () => {
    expect(detectReportKind(pdf("1 0 obj<</Type/Catalog>>"))).toBe("pdf");
  });

  it("recognises HTML with a doctype", () => {
    expect(detectReportKind(html("<!DOCTYPE html>\n<html><body>Report</body></html>"))).toBe(
      "html",
    );
  });

  it("recognises HTML without a doctype", () => {
    expect(detectReportKind(html("<html>\n<body>Report</body>\n</html>"))).toBe("html");
  });

  it("ignores leading whitespace and a byte-order mark", () => {
    // Both are routinely added by editors and export tools.
    expect(detectReportKind(html("﻿\n  <!doctype html><html></html>"))).toBe("html");
  });

  it("is not case-sensitive about the tag", () => {
    expect(detectReportKind(html("<!DocType HTML><HTML></HTML>"))).toBe("html");
  });

  it("accepts a generator that opens with a comment", () => {
    expect(
      detectReportKind(
        html("<!-- generated by the evaluation tool -->\n<html><body>x</body></html>"),
      ),
    ).toBe("html");
  });

  it("refuses a file that is neither", () => {
    // The kind decides how the file is served. Guessing wrong means serving something
    // unknown as a web page, so anything unrecognised is refused rather than assumed.
    expect(detectReportKind(Buffer.from("just some notes"))).toBeNull();
    expect(detectReportKind(Buffer.from("name,score\nAyesha,80"))).toBeNull();
    expect(detectReportKind(Buffer.from([0x50, 0x4b, 0x03, 0x04]))).toBeNull(); // a zip
  });

  it("is not fooled by a name — it reads the bytes", () => {
    // A PDF renamed report.html is still a PDF, and is served as one.
    expect(detectReportKind(pdf())).toBe("pdf");
  });

  it("refuses a bare fragment with no html, head or body", () => {
    expect(detectReportKind(Buffer.from("<p>just a paragraph</p>"))).toBeNull();
  });
});

describe("validateReport", () => {
  it("accepts a PDF and says so", () => {
    expect(validateReport(pdf(), MAX)).toEqual({ kind: "pdf" });
  });

  it("accepts HTML and says so", () => {
    expect(validateReport(html("<html><body>x</body></html>"), MAX)).toEqual({ kind: "html" });
  });

  it("refuses an empty file", () => {
    expect(validateReport(Buffer.alloc(0), MAX)).toEqual({ problem: "empty" });
  });

  it("refuses a file over the limit", () => {
    expect(validateReport(pdf("x".repeat(200)), 100)).toEqual({ problem: "too_large" });
  });

  it("refuses anything that is not one of the two", () => {
    expect(validateReport(Buffer.from("hello"), MAX)).toEqual({ problem: "unsupported" });
  });

  it("checks size before kind, so a huge wrong file is not sniffed", () => {
    expect(validateReport(Buffer.from("x".repeat(500)), 100)).toEqual({ problem: "too_large" });
  });
});

describe("reportContentType", () => {
  it("serves a PDF as a PDF", () => {
    expect(reportContentType("pdf")).toBe("application/pdf");
  });

  it("serves HTML with a charset, or accented names come out as mojibake", () => {
    expect(reportContentType("html")).toBe("text/html; charset=utf-8");
  });
});

describe("safeReportFilename", () => {
  it("keeps an ordinary name and fixes the extension to match the content", () => {
    expect(safeReportFilename("evaluation-results.pdf", "pdf")).toBe("evaluation-results.pdf");
    expect(safeReportFilename("evaluation-results.html", "html")).toBe("evaluation-results.html");
  });

  it("corrects an extension that lies about the file", () => {
    expect(safeReportFilename("results.html", "pdf")).toBe("results.pdf");
  });

  it("strips anything a filename could smuggle into a header", () => {
    expect(safeReportFilename('a"b\nc.pdf', "pdf")).toBe("a_b_c.pdf");
    expect(safeReportFilename("../../etc/passwd", "pdf")).toBe("passwd.pdf");
  });

  it("falls back rather than producing a name that is only an extension", () => {
    expect(safeReportFilename("", "html")).toBe("report.html");
    expect(safeReportFilename("...", "pdf")).toBe("report.pdf");
    expect(safeReportFilename("___.pdf", "pdf")).toBe("report.pdf");
  });
});
